import gradio as gr

from gui.ui.components.render_mdfile import MarkdownDocumentView
from gui.ui.events.left_sidebar import bind_left_sidebar_events
from gui.ui.events.tab_improvement import bind_tab_improvement_events
from gui.ui.events.tab_initial import bind_tab_initial_events
from gui.ui.events.tab_lci import bind_tab_lci_events
from gui.ui.events.tab_plan import bind_tab_plan_events
from gui.ui.events.tab_result import bind_tab_result_events
from gui.ui.events.tab_terminal import bind_tab_terminal_events


def bind_ui_events(
    *,
    open_init_btn: gr.Button,
    start_lca_btn: gr.Button,
    execute_lca_btn: gr.Button,
    view_lca_result_btn: gr.Button,
    ref_upload_file: gr.File,
    right_tabs: gr.Tabs,
    output_console: gr.Textbox,
    status: gr.Textbox,
    clear_btn: gr.Button,
    stop_btn: gr.Button,
    init_check_btn: gr.Button,
    init_check_status_values: list[gr.Markdown],
    agent_dropdown: gr.Dropdown,
    codex_model: gr.Textbox,
    claude_model: gr.Textbox,
    opencode_model: gr.Dropdown,
    pi_model: gr.Dropdown,
    opencode_refresh_btn: gr.Button,
    pi_refresh_btn: gr.Button,
    codex_probe_btn: gr.Button,
    claude_probe_btn: gr.Button,
    opencode_probe_btn: gr.Button,
    pi_probe_btn: gr.Button,
    codex_probe_status: gr.Markdown,
    claude_probe_status: gr.Markdown,
    opencode_probe_status: gr.Markdown,
    pi_probe_status: gr.Markdown,
    agent_save_btn: gr.Button,
    init_openlca_port: gr.Number,
    dev_gui_port: gr.Number,
    dev_ports_save_btn: gr.Button,
    close_lci_mapping_btn: gr.Button,
    bom_json: gr.JSON,
    bom_warning: gr.Markdown,
    download_bom_btn: gr.DownloadButton,
    mapping_json: gr.JSON,
    mapping_warning: gr.Markdown,
    download_mapping_btn: gr.DownloadButton,
    run_result_state: gr.State,
    result_heading: gr.Markdown,
    success_panel: gr.Column,
    failure_panel: gr.Column,
    failure_markdown: gr.Markdown,
    show_lci_btn: gr.Button,
    modify_rerun_btn: gr.Button,
    improvement_view: MarkdownDocumentView,
    close_improvement_btn: gr.Button,
    upload_improvement_btn: gr.UploadButton,
    execute_improvement_btn: gr.Button,
    plan_view: MarkdownDocumentView,
    close_plan_btn: gr.Button,
    upload_plan_btn: gr.UploadButton,
    report_view: MarkdownDocumentView,
    report_warning: gr.Markdown,
    download_report_btn: gr.DownloadButton,
    init_check_ok_state: gr.State,
    plan_ready_state: gr.State,
    improvement_ready_state: gr.State,
) -> None:
    """Bind events for the currently supported GUI features."""
    bind_left_sidebar_events(
        open_init_btn=open_init_btn,
        right_tabs=right_tabs,
        agent_dropdown=agent_dropdown,
        codex_model=codex_model,
        claude_model=claude_model,
        opencode_model=opencode_model,
        pi_model=pi_model,
        init_openlca_port=init_openlca_port,
        dev_gui_port=dev_gui_port,
    )

    bind_tab_terminal_events(
        clear_btn=clear_btn,
        stop_btn=stop_btn,
        output_console=output_console,
        status=status,
    )

    bind_tab_initial_events(
        init_check_btn=init_check_btn,
        init_check_status_values=init_check_status_values,
        dev_ports_save_btn=dev_ports_save_btn,
        agent_dropdown=agent_dropdown,
        codex_model=codex_model,
        claude_model=claude_model,
        opencode_model=opencode_model,
        pi_model=pi_model,
        opencode_refresh_btn=opencode_refresh_btn,
        pi_refresh_btn=pi_refresh_btn,
        codex_probe_btn=codex_probe_btn,
        claude_probe_btn=claude_probe_btn,
        opencode_probe_btn=opencode_probe_btn,
        pi_probe_btn=pi_probe_btn,
        codex_probe_status=codex_probe_status,
        claude_probe_status=claude_probe_status,
        opencode_probe_status=opencode_probe_status,
        pi_probe_status=pi_probe_status,
        agent_save_btn=agent_save_btn,
        init_openlca_port=init_openlca_port,
        dev_gui_port=dev_gui_port,
        execute_lca_btn=execute_lca_btn,
        execute_improvement_btn=execute_improvement_btn,
        init_check_ok_state=init_check_ok_state,
        plan_ready_state=plan_ready_state,
        improvement_ready_state=improvement_ready_state,
    )

    bind_tab_plan_events(
        start_lca_btn=start_lca_btn,
        plan_view=plan_view,
        close_plan_btn=close_plan_btn,
        upload_plan_btn=upload_plan_btn,
        execute_lca_btn=execute_lca_btn,
        right_tabs=right_tabs,
        plan_ready_state=plan_ready_state,
        init_check_ok_state=init_check_ok_state,
    )

    revision_execute_event = bind_tab_improvement_events(
        modify_rerun_btn=modify_rerun_btn,
        improvement_view=improvement_view,
        close_improvement_btn=close_improvement_btn,
        upload_improvement_btn=upload_improvement_btn,
        execute_improvement_btn=execute_improvement_btn,
        right_tabs=right_tabs,
        init_check_ok_state=init_check_ok_state,
        improvement_ready_state=improvement_ready_state,
        ref_upload_file=ref_upload_file,
        output_console=output_console,
        status=status,
        run_result_state=run_result_state,
    )

    bind_tab_lci_events(
        show_lci_btn=show_lci_btn,
        close_lci_mapping_btn=close_lci_mapping_btn,
        right_tabs=right_tabs,
        bom_json=bom_json,
        bom_warning=bom_warning,
        download_bom_btn=download_bom_btn,
        mapping_json=mapping_json,
        mapping_warning=mapping_warning,
        download_mapping_btn=download_mapping_btn,
    )

    bind_tab_result_events(
        view_lca_result_btn=view_lca_result_btn,
        execute_lca_btn=execute_lca_btn,
        plan_view=plan_view,
        report_view=report_view,
        plan_ready_state=plan_ready_state,
        improvement_ready_state=improvement_ready_state,
        execute_improvement_btn=execute_improvement_btn,
        revision_execute_event=revision_execute_event,
        init_check_ok_state=init_check_ok_state,
        ref_upload_file=ref_upload_file,
        output_console=output_console,
        status=status,
        run_result_state=run_result_state,
        right_tabs=right_tabs,
        result_heading=result_heading,
        success_panel=success_panel,
        failure_panel=failure_panel,
        failure_markdown=failure_markdown,
        report_warning=report_warning,
        download_report_btn=download_report_btn,
    )
