import re
from html import escape
from pathlib import Path

from functions.utils.file_loader.private_utils.template_metadata import (
    split_front_matter,
)

_TOC_HEADING = re.compile(r"^(#{2,3})\s+(.*)$", re.MULTILINE)


def add_toc_anchors(
    content: str,
    anchor_prefix: str = "plan-header",
) -> str:
    """Add stable targets matching links generated by ``extract_plan_toc``."""
    heading_count = 0

    def add_anchor(match: re.Match[str]) -> str:
        nonlocal heading_count
        heading_count += 1
        return (
            f'<a id="{anchor_prefix}-{heading_count}"></a>\n\n'
            f"{match.group(1)} {match.group(2)}"
        )

    return _TOC_HEADING.sub(add_anchor, content)


def extract_plan_toc(
    filepath: Path,
    title: str = "📋 计划目录导航",
    anchor_prefix: str = "plan-header",
) -> str:
    """
    扫描 Markdown 文件，提取二级和三级标题并生成 HTML 目录导航。
    """
    if not filepath.exists():
        return ""
    try:
        content = filepath.read_text(encoding="utf-8-sig")
    except Exception:
        return ""

    _, content = split_front_matter(content)

    toc_lines = ["<div class='toc-wrapper'>", f"<h4>{title}</h4>"]
    header_count = 0
    for match in _TOC_HEADING.finditer(content):
        level_hashes = match.group(1)
        heading_title = match.group(2).strip()
        level = len(level_hashes)

        header_count += 1
        anchor_id = f"{anchor_prefix}-{header_count}"
        indent_class = f"toc-level-{level}"
        toc_lines.append(
            f"<a href='#{escape(anchor_id)}' "
            f"class='toc-link {indent_class}'>{escape(heading_title)}</a>"
        )

    toc_lines.append("</div>")
    return "\n".join(toc_lines)
